title: Common Workflow Language (CWL)
baseurl: ""
url: "https://www.commonwl.org"
author: "Common Workflow Language (CWL)"
# email:             your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The Common Workflow Language (CWL) is an open standard for describing
  analysis workflows and tools in a way that makes them portable and scalable
  across a variety of software and hardware environments, from workstations
  to cluster, cloud, and high performance computing (HPC) environments.
  CWL is designed to meet the needs of data-intensive science, such as
  Bioinformatics, Medical Imaging, Astronomy, High Energy Physics, and
  Machine Learning.

github_url: https://github.com/common-workflow-language/
twitter_url: https://mobile.twitter.com/commonwl

# SEO - jekyll-seo-tag
logo: "/CWL-Logo-Header.png"
twitter:
  - username: commonwl
  - card: summary
social:
  name: Common Workflow Language (CWL)
  links:
    - https://www.youtube.com/c/CommonWLorgStandard
    - https://twitter.com/commonwl
locale: en_US
# google_site_verification:

show_excerpts: false # set to true to show excerpts on the homepage

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

exclude:
  - _archive/
  - _scratch/
  - Notes
  - LICENSE
  - README.md
  - fresh.gif

sass:
  sass_dir: _sass
  # style: compressed

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false
